### ISSUE TITLE
Possible to create a count-in or preroll to the record function?

### ISSUE THREAD

**Issue by flopass** [kilpatrickaudio/CARBON#64] opened 2017-03-21 01:05 UTC
It's very useful on my Analog Keys to load a bar or two of preroll so I can ready myself for recording to the sequencer. Is it possible to add this as an option for Carbon?

**Comment by kilpatrickaudio** [comment] 2017-04-05 23:53
Duplicate of issue #20 which is scheduled to be worked on.

**Closed by kilpatrickaudio** 2017-04-05 23:53 UTC

**Comment by flopass** [comment] 2017-07-03 17:21
I know this has merged with issue #20, but is there any progress with this possible feature implementation?

**Comment by kilpatrickaudio** [comment] 2017-07-03 17:25
We will try to have time for another release this fall and will likely tackle the lead-in request at this time.
